import { useMemo, useState } from 'react'
import { ArrowRight, FolderOpen, Search } from 'lucide-react'
import type { Case } from '../types'

export function Cases({ cases, onCase, onNew }: { cases: Case[]; onCase: (id: string) => void; onNew: () => void }) {
  const [search, setSearch] = useState('')
  const visible = useMemo(() => cases.filter(item => `${item.case_number} ${item.police_station}`.toLowerCase().includes(search.toLowerCase())), [cases, search])
  return <main className="min-h-screen bg-canvas px-8 py-8 lg:px-10"><div className="mx-auto max-w-[1320px]"><div className="flex flex-wrap items-end justify-between gap-4"><div><div className="eyebrow">Case register</div><h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink">Cases</h1><p className="mt-2 text-sm text-slate-500">Open an existing investigation workspace or start a new analysis.</p></div><button onClick={onNew} className="rounded-lg bg-teal-700 px-4 py-2.5 text-sm font-semibold text-white">New analysis</button></div><label className="relative mt-7 block max-w-md"><Search className="absolute left-3 top-3 text-slate-400" size={16} /><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Search case ID or police station" className="w-full rounded-lg border border-slate-200 bg-white py-2.5 pl-9 pr-3 text-sm" /></label><section className="panel mt-5 overflow-hidden">{visible.length ? visible.map(item => <button key={item.id} onClick={() => onCase(item.id)} className="grid w-full grid-cols-[1fr_220px_120px_26px] items-center gap-4 border-b border-slate-100 px-5 py-4 text-left last:border-0 hover:bg-slate-50"><div><div className="flex items-center gap-2"><span className="text-sm font-semibold">{item.case_number}</span>{item.is_demo && <span className="chip border-sky-200 bg-sky-50 text-sky-700">Synthetic demo</span>}</div><div className="mt-1 text-xs text-slate-400">{item.language}</div></div><div className="text-xs text-slate-500">{item.police_station}</div><div className="text-xs font-semibold capitalize text-teal-700">{item.status}</div><ArrowRight size={15} className="text-slate-300" /></button>) : <div className="grid min-h-48 place-items-center p-6 text-center"><div><FolderOpen className="mx-auto text-slate-300" /><p className="mt-3 text-sm font-medium">No matching cases</p><p className="mt-1 text-xs text-slate-400">Adjust the search or create a new analysis.</p></div></div>}</section></div></main>
}
