import { useQuery } from '@tanstack/react-query'
import { AlertTriangle, ClipboardCheck, MessageCircleQuestion, ShieldAlert } from 'lucide-react'
import { api } from '../../api/client'
import { CitationButton } from '../../components/CitationButton'
import { Loading } from '../../components/Loading'
import type { Citation } from '../../types'
import { useLanguage, useTranslatedTexts } from '../../i18n/LanguageContext'

export function DefenseView({ caseId, onCitation }: { caseId: string; onCitation: (value: Citation) => void }) {
  const query = useQuery({ queryKey: ['defense', caseId], queryFn: () => api.defense(caseId) })
  const { t } = useLanguage()
  const items = query.data || []
  const translated = useTranslatedTexts(items.flatMap(item => [item.title, item.weakness, item.io_action, item.recommended_correction, ...item.defense_questions, ...item.differences.flatMap(d => [d.role, d.value])]))
  if (query.isLoading) return <Loading />
  return <div className="mx-auto max-w-[1220px]"><div className="eyebrow">{t('Court-readiness review')}</div><h2 className="mt-1.5 text-xl font-semibold">{t('Defense Assistant')}</h2><p className="mt-1 text-xs text-slate-500">{t('Potential challenges are generated from detected gaps and inconsistencies. They are prompts for IO verification, not legal conclusions.')}</p>
    <div className="mt-5 space-y-4">{items.map(item => { const tr = (value?: string) => value ? translated.translated.get(value) || value : ''; return <article key={item.id} className="panel overflow-hidden"><div className="border-b border-slate-100 bg-amber-50/50 p-5"><div className="flex items-start gap-3"><ShieldAlert className="mt-0.5 text-amber-700" size={19} /><div><div className="eyebrow">{t('Potential defense weakness')}</div><h3 className="mt-1 text-base font-semibold">{tr(item.title)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">{tr(item.weakness)}</p></div></div></div><div className="grid gap-5 p-5 lg:grid-cols-2"><section><div className="flex items-center gap-2 text-xs font-bold"><MessageCircleQuestion size={15} className="text-sky-700" />{t('Questions the defense may raise')}</div><ul className="mt-3 space-y-2 text-xs leading-5 text-slate-600">{item.defense_questions.map(question => <li key={question} className="rounded border border-slate-100 bg-slate-50 p-2.5">{tr(question)}</li>)}</ul></section><section><div className="flex items-center gap-2 text-xs font-bold"><ClipboardCheck size={15} className="text-teal-700" />{t('IO preparation')}</div><p className="mt-3 rounded border border-teal-100 bg-teal-50 p-3 text-xs leading-5 text-teal-900">{tr(item.io_action)}</p>{item.recommended_correction && <p className="mt-2 text-xs leading-5 text-slate-500"><b>{t('Recommended correction')}:</b> {tr(item.recommended_correction)}</p>}<div className="mt-3 flex flex-wrap gap-2">{item.relevant_sources.map((citation, index) => <CitationButton key={`${citation.chunk_id}-${index}`} citation={citation} onOpen={onCitation} />)}</div></section></div>{item.differences.length > 0 && <div className="border-t border-slate-100 p-5"><div className="text-xs font-bold">{t('Detected document differences')}</div><div className="mt-3 grid gap-2 sm:grid-cols-2">{item.differences.map(difference => <div key={`${difference.document}-${difference.value}`} className="rounded border border-slate-100 p-2.5 text-xs"><div className="font-semibold">{difference.document}</div><div className="mt-1 text-slate-500">{tr(difference.role)} · {tr(difference.value)}</div></div>)}</div></div>}<div className="flex items-center gap-2 border-t border-slate-100 px-5 py-3 text-[11px] text-amber-800"><AlertTriangle size={13} />{t('Human verification required')}</div></article>})}</div>{items.length === 0 && <div className="panel p-8 text-center text-sm text-slate-400">{t('No defense-oriented weaknesses have been generated yet.')}</div>}</div>
}
