import { FormEvent, useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { AlertTriangle, BookOpen, Search } from 'lucide-react'
import { api } from '../../api/client'
import { Loading } from '../../components/Loading'
import { useLanguage } from '../../i18n/LanguageContext'

export function PrecedentsView({ caseId }: { caseId: string }) {
  const { t } = useLanguage()
  const client = useQueryClient(); const [file, setFile] = useState<File>(); const [title, setTitle] = useState(''); const [court, setCourt] = useState(''); const [year, setYear] = useState('')
  const judgments = useQuery({ queryKey: ['judgments'], queryFn: api.judgments }); const analysis = useQuery({ queryKey: ['precedents', caseId], queryFn: () => api.precedents(caseId) })
  const upload = useMutation({ mutationFn: () => api.uploadJudgment(file!, title, court, year), onSuccess: async () => { setFile(undefined); setTitle(''); setCourt(''); setYear(''); await client.invalidateQueries({ queryKey: ['judgments'] }); await client.invalidateQueries({ queryKey: ['precedents', caseId] }) } })
  const submit = (event: FormEvent) => { event.preventDefault(); if (file) upload.mutate() }
  if (judgments.isLoading || analysis.isLoading) return <Loading />
  return <div className="mx-auto max-w-[1220px]"><div className="eyebrow">{t('Approved local corpus')}</div><h2 className="mt-1.5 text-xl font-semibold">{t('Precedent review')}</h2><p className="mt-1 text-xs text-slate-500">{t('Only judgments imported into this local corpus are searched. Results are research prompts and require legal review.')}</p><form onSubmit={submit} className="panel mt-5 grid gap-3 p-5 md:grid-cols-[1fr_1fr_110px_auto]"><input value={title} onChange={event => setTitle(event.target.value)} placeholder={t('Judgment title')} className="rounded border border-slate-200 px-3 py-2 text-xs" /><input value={court} onChange={event => setCourt(event.target.value)} placeholder={t('Court')} className="rounded border border-slate-200 px-3 py-2 text-xs" /><input value={year} onChange={event => setYear(event.target.value)} placeholder={t('Year')} className="rounded border border-slate-200 px-3 py-2 text-xs" /><label className="cursor-pointer rounded bg-slate-800 px-3 py-2 text-center text-xs font-semibold text-white">{file ? file.name : t('Choose PDF')}<input type="file" accept="application/pdf,.pdf" className="hidden" onChange={event => setFile(event.target.files?.[0])} /></label><button disabled={!file || upload.isPending} className="rounded bg-teal-700 px-3 py-2 text-xs font-semibold text-white disabled:opacity-40 md:col-span-4">{upload.isPending ? t('Importing…') : t('Import judgment into local corpus')}</button></form><div className="mt-5 grid gap-5 lg:grid-cols-[.8fr_1.2fr]"><section className="panel p-5"><div className="flex items-center gap-2 text-xs font-bold"><BookOpen size={15} className="text-sky-700" />{t('Imported judgments')} ({judgments.data?.length || 0})</div><div className="mt-4 space-y-2">{judgments.data?.map(item => <div key={item.id} className="rounded border border-slate-100 p-3 text-xs"><div className="font-semibold">{item.title}</div><div className="mt-1 text-slate-500">{item.court || t('Court not specified')} · {item.judgment_year || t('Year not specified')} · {item.page_count} {t('pages')}</div></div>)}</div>{judgments.data?.length === 0 && <p className="mt-4 text-xs text-slate-400">{t('No judgments imported yet.')}</p>}</section><section className="panel p-5"><div className="flex items-center gap-2 text-xs font-bold"><Search size={15} className="text-teal-700" />{t('Case-relevant precedent insights')}</div><p className="mt-4 whitespace-pre-wrap text-sm leading-7 text-slate-600">{analysis.data?.insights}</p>{analysis.data?.review_required && <div className="mt-4 flex items-center gap-2 rounded border border-amber-200 bg-amber-50 p-3 text-xs text-amber-800"><AlertTriangle size={14} />{t('Human/legal review required.')}</div>}<div className="mt-4 flex flex-wrap gap-2">{analysis.data?.citations.map(citation => <span key={citation.chunk_id} className="rounded border border-slate-200 bg-white px-2.5 py-1.5 text-xs text-slate-600">{citation.label}</span>)}</div></section></div></div>
}
